version: "3.8"

services:
  mongodb-product:
    image: mongo:7
    container_name: mongodb-product
    ports:
      - "27017:27017"
    volumes:
      - product_data:/data/db

volumes:
  product_data:
